version: "2"

services:
  elasticsearch:
    image: "josperrod17/imdb-api:elasticsearch"
    hostname: "elasticsearch"
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=https://app.elasticvue.com, http://cerebro:9000
    ports:
      - "9200:9200"
      - "9300:9300"
  cerebro:
    image: lmenezes/cerebro
    container_name: cerebro
    hostname: "cerebro"
    ports:
      - "9000:9000"
    command:
      - -Dhosts.0.host=http://elasticsearch:9200
